'use client';
import { fetchWithCsrf } from '@/lib/api';
import { ImageIcon, Loader2, Search, Upload, X } from 'lucide-react';
import { ChangeEvent,useCallback,useEffect,useMemo,useState } from 'react';
type Asset={url:string;product_title?:string|null;alt_text?:string|null};
async function message(response:Response,fallback:string){try{const data=await response.json();return data.error?.message||data.message||fallback}catch{return fallback}}
function name(asset:Asset){try{return asset.product_title||asset.alt_text||new URL(asset.url,window.location.origin).pathname.split('/').pop()||'Store image'}catch{return asset.product_title||asset.alt_text||'Store image'}}
export function AdsCreativeMediaPicker({open,onClose,onSelect}:{open:boolean;onClose:()=>void;onSelect:(url:string)=>void}){
 const [assets,setAssets]=useState<Asset[]>([]),[loading,setLoading]=useState(false),[uploading,setUploading]=useState(false),[search,setSearch]=useState(''),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetchWithCsrf('/api/pd/stores/me/media?limit=100',{credentials:'include'});if(!response.ok)throw new Error(await message(response,'Unable to load your media'));const data=await response.json();setAssets(data.data||[])}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load your media')}finally{setLoading(false)}},[]);
 useEffect(()=>{if(open)void load()},[open,load]);
 const filtered=useMemo(()=>{const value=search.trim().toLowerCase();return value?assets.filter(asset=>`${name(asset)} ${asset.url}`.toLowerCase().includes(value)):assets},[assets,search]);
 const upload=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;setError('');setUploading(true);try{if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Upload a JPG, PNG, or WebP image.');if(file.size>10*1024*1024)throw new Error('Image must be smaller than 10 MB.');const presign=await fetchWithCsrf('/api/pd/files/presign',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:file.name,content_type:file.type,file_size:file.size,purpose:'product_image'})});if(!presign.ok)throw new Error(await message(presign,'Unable to prepare upload'));const data=await presign.json();const result=await fetch(data.upload_url,{method:'PUT',headers:{'Content-Type':file.type},body:file});if(!result.ok)throw new Error('Image upload failed.');if(!data.public_url)throw new Error('The uploaded image URL is unavailable.');onSelect(data.public_url);onClose()}catch(reason){setError(reason instanceof Error?reason.message:'Image upload failed')}finally{setUploading(false)}};
 if(!open)return null;
 return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/70 p-4" role="dialog" aria-modal="true" aria-labelledby="ads-media-title"><div className="w-full max-w-4xl rounded-3xl bg-white shadow-2xl"><header className="flex items-start justify-between border-b p-5"><div><h2 id="ads-media-title" className="text-xl font-black">Choose creative image</h2><p className="text-sm text-slate-500">Upload a new image or reuse one from your store media library.</p></div><button type="button" onClick={onClose} aria-label="Close media library" className="rounded-xl p-2 hover:bg-slate-100"><X/></button></header><div className="space-y-4 p-5">{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><span className="sr-only">Search media</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search store media" className="w-full rounded-xl border py-3 pl-10 pr-3 text-sm"/></label><label className="inline-flex cursor-pointer items-center justify-center gap-2 rounded-xl bg-emerald-600 px-5 py-3 text-sm font-black text-white">{uploading?<Loader2 className="h-4 w-4 animate-spin"/>:<Upload className="h-4 w-4"/>}{uploading?'Uploading…':'Upload image'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={upload} className="hidden"/></label></div>{loading?<div className="flex justify-center py-16"><Loader2 className="h-8 w-8 animate-spin text-emerald-600"/></div>:filtered.length?<div className="grid max-h-[55vh] grid-cols-2 gap-3 overflow-y-auto sm:grid-cols-3 md:grid-cols-4">{filtered.map(asset=><button key={asset.url} type="button" onClick={()=>{onSelect(asset.url);onClose()}} className="group overflow-hidden rounded-2xl border text-left hover:border-emerald-500 hover:shadow-lg"><img src={asset.url} alt={name(asset)} className="aspect-square w-full bg-slate-100 object-cover"/><p className="truncate p-3 text-xs font-bold">{name(asset)}</p></button>)}</div>:<div className="rounded-2xl border border-dashed py-14 text-center text-sm text-slate-500"><ImageIcon className="mx-auto mb-2 h-9 w-9 text-slate-300"/>No store images found.</div>}</div></div></div>}
