'use client';
type Point={stat_date:string;impressions:string|number;clicks:string|number;conversions:string|number;spend:string|number;revenue:string|number};
const W=720,H=190,P=12;
function path(values:number[]){const max=Math.max(...values,1);return values.map((value,index)=>`${index?'L':'M'} ${P+(index/Math.max(values.length-1,1))*(W-P*2)} ${H-P-(value/max)*(H-P*2)}`).join(' ')}
export function AdsPerformanceCharts({daily}:{daily:Point[]}){
 if(!daily.length)return <div className="mt-5 rounded-2xl border border-dashed p-10 text-center text-sm text-slate-400">No performance data for this period.</div>;
 const impressionPath=path(daily.map(p=>Number(p.impressions))),clickPath=path(daily.map(p=>Number(p.clicks))),spendPath=path(daily.map(p=>Number(p.spend))),revenuePath=path(daily.map(p=>Number(p.revenue)));
 return <div className="mt-6 grid gap-4 lg:grid-cols-2"><Chart title="Reach and engagement" subtitle="Impressions and clicks" lines={[{path:impressionPath,color:'#059669',label:'Impressions'},{path:clickPath,color:'#f59e0b',label:'Clicks'}]} daily={daily}/><Chart title="Spend and attributed revenue" subtitle="TND by day" lines={[{path:spendPath,color:'#dc2626',label:'Spend'},{path:revenuePath,color:'#2563eb',label:'Revenue'}]} daily={daily}/></div>
}
function Chart({title,subtitle,lines,daily}:{title:string;subtitle:string;lines:{path:string;color:string;label:string}[];daily:Point[]}){return <figure className="min-w-0 rounded-2xl border border-slate-100 bg-slate-50 p-4"><figcaption><p className="font-black text-slate-900">{title}</p><p className="text-xs text-slate-500">{subtitle}</p></figcaption><div className="mt-3 flex flex-wrap gap-3">{lines.map(line=><span key={line.label} className="inline-flex items-center gap-1 text-[11px] font-bold text-slate-600"><i className="h-2 w-2 rounded-full" style={{background:line.color}}/>{line.label}</span>)}</div><div className="mt-2 overflow-x-auto" dir="ltr"><svg viewBox={`0 0 ${W} ${H}`} className="h-48 min-w-[520px] w-full" role="img" aria-label={`${title} from ${daily[0].stat_date} to ${daily[daily.length-1].stat_date}`}>{[.25,.5,.75].map(value=><line key={value} x1={P} x2={W-P} y1={H*value} y2={H*value} stroke="#e2e8f0" strokeDasharray="4 5"/>)}{lines.map(line=><path key={line.label} d={line.path} fill="none" stroke={line.color} strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/> )}</svg></div><div className="flex justify-between text-[10px] font-semibold text-slate-400" dir="ltr"><span>{new Date(daily[0].stat_date).toLocaleDateString()}</span><span>{new Date(daily[daily.length-1].stat_date).toLocaleDateString()}</span></div></figure>}
