/**
 * Standard error response shape for all PandaMarket APIs.
 * Codes follow the catalog in `ai instructions/error-codes.md`.
 */

export interface IPdErrorResponse {
  error: {
    code: string; // PD_XXX_XXX
    message: string; // Human-readable message
    details?: Record<string, unknown>;
    request_id?: string;
  };
}

/**
 * Catalog of all error codes (mirrors error-codes.md).
 * Use these constants when throwing/catching to avoid typos.
 */
export const PdErrorCode = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'PD_AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'PD_AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'PD_AUTH_TOKEN_INVALID',
  AUTH_REFRESH_EXPIRED: 'PD_AUTH_REFRESH_EXPIRED',
  AUTH_EMAIL_EXISTS: 'PD_AUTH_EMAIL_EXISTS',
  AUTH_WEAK_PASSWORD: 'PD_AUTH_WEAK_PASSWORD',
  AUTH_ACCOUNT_SUSPENDED: 'PD_AUTH_ACCOUNT_SUSPENDED',

  // Permissions
  PERM_FORBIDDEN: 'PD_PERM_FORBIDDEN',
  PERM_NOT_OWNER: 'PD_PERM_NOT_OWNER',
  PERM_ADMIN_ONLY: 'PD_PERM_ADMIN_ONLY',
  PERM_PLAN_REQUIRED: 'PD_PERM_PLAN_REQUIRED',

  // Store
  STORE_NOT_FOUND: 'PD_STORE_NOT_FOUND',
  STORE_SUBDOMAIN_TAKEN: 'PD_STORE_SUBDOMAIN_TAKEN',
  STORE_DOMAIN_TAKEN: 'PD_STORE_DOMAIN_TAKEN',
  STORE_SUSPENDED: 'PD_STORE_SUSPENDED',
  STORE_NOT_VERIFIED: 'PD_STORE_NOT_VERIFIED',

  // Product
  PRODUCT_NOT_FOUND: 'PD_PRODUCT_NOT_FOUND',
  PRODUCT_QUOTA_EXCEEDED: 'PD_PRODUCT_QUOTA_EXCEEDED',
  PRODUCT_IMAGE_QUOTA: 'PD_PRODUCT_IMAGE_QUOTA',
  PRODUCT_PENDING_APPROVAL: 'PD_PRODUCT_PENDING_APPROVAL',
  PRODUCT_OUT_OF_STOCK: 'PD_PRODUCT_OUT_OF_STOCK',
  PRODUCT_INVALID_TYPE: 'PD_PRODUCT_INVALID_TYPE',

  // Order
  ORDER_NOT_FOUND: 'PD_ORDER_NOT_FOUND',
  ORDER_ALREADY_FULFILLED: 'PD_ORDER_ALREADY_FULFILLED',
  ORDER_ALREADY_CANCELLED: 'PD_ORDER_ALREADY_CANCELLED',
  ORDER_CANNOT_CANCEL: 'PD_ORDER_CANNOT_CANCEL',
  ORDER_EMPTY_CART: 'PD_ORDER_EMPTY_CART',

  // Payments
  PAY_INIT_FAILED: 'PD_PAY_INIT_FAILED',
  PAY_VERIFICATION_FAILED: 'PD_PAY_VERIFICATION_FAILED',
  PAY_ALREADY_CAPTURED: 'PD_PAY_ALREADY_CAPTURED',
  PAY_MANDAT_UPLOAD_FAILED: 'PD_PAY_MANDAT_UPLOAD_FAILED',
  PAY_MANDAT_ALREADY_REVIEWED: 'PD_PAY_MANDAT_ALREADY_REVIEWED',
  PAY_INVALID_GATEWAY: 'PD_PAY_INVALID_GATEWAY',

  // Wallet
  WALLET_INSUFFICIENT_FUNDS: 'PD_WALLET_INSUFFICIENT_FUNDS',
  WALLET_MIN_WITHDRAWAL: 'PD_WALLET_MIN_WITHDRAWAL',
  WALLET_FUNDS_PENDING: 'PD_WALLET_FUNDS_PENDING',
  WALLET_PAYOUT_FAILED: 'PD_WALLET_PAYOUT_FAILED',

  // KYC
  KYC_ALREADY_SUBMITTED: 'PD_KYC_ALREADY_SUBMITTED',
  KYC_ALREADY_VERIFIED: 'PD_KYC_ALREADY_VERIFIED',
  KYC_INVALID_DOCUMENT: 'PD_KYC_INVALID_DOCUMENT',
  KYC_REJECTED: 'PD_KYC_REJECTED',

  // AI
  AI_INSUFFICIENT_TOKENS: 'PD_AI_INSUFFICIENT_TOKENS',
  AI_JOB_NOT_FOUND: 'PD_AI_JOB_NOT_FOUND',
  AI_JOB_FAILED: 'PD_AI_JOB_FAILED',
  AI_SERVICE_UNAVAILABLE: 'PD_AI_SERVICE_UNAVAILABLE',
  AI_FILE_TOO_LARGE: 'PD_AI_FILE_TOO_LARGE',

  // Reports
  REPORT_DUPLICATE: 'PD_REPORT_DUPLICATE',
  REPORT_NOT_FOUND: 'PD_REPORT_NOT_FOUND',
  REPORT_ALREADY_RESOLVED: 'PD_REPORT_ALREADY_RESOLVED',

  // Files
  FILE_TOO_LARGE: 'PD_FILE_TOO_LARGE',
  FILE_INVALID_TYPE: 'PD_FILE_INVALID_TYPE',
  FILE_UPLOAD_FAILED: 'PD_FILE_UPLOAD_FAILED',
  FILE_PRESIGN_FAILED: 'PD_FILE_PRESIGN_FAILED',

  // Subscriptions
  SUB_ALREADY_ACTIVE: 'PD_SUB_ALREADY_ACTIVE',
  SUB_DOWNGRADE_BLOCKED: 'PD_SUB_DOWNGRADE_BLOCKED',
  SUB_EXPIRED: 'PD_SUB_EXPIRED',
  SUB_PAYMENT_FAILED: 'PD_SUB_PAYMENT_FAILED',

  // API Keys
  KEY_INVALID: 'PD_KEY_INVALID',
  KEY_EXPIRED: 'PD_KEY_EXPIRED',
  KEY_SCOPE_DENIED: 'PD_KEY_SCOPE_DENIED',
  KEY_RATE_LIMITED: 'PD_KEY_RATE_LIMITED',

  // Generic
  VALIDATION_ERROR: 'PD_VALIDATION_ERROR',
  NOT_FOUND: 'PD_NOT_FOUND',
  RATE_LIMITED: 'PD_RATE_LIMITED',
  INTERNAL_ERROR: 'PD_INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'PD_SERVICE_UNAVAILABLE',
} as const;

export type PdErrorCodeValue = (typeof PdErrorCode)[keyof typeof PdErrorCode];
